### ISSUE TITLE
Allow for use of command line parameters

### ISSUE THREAD

**Issue by drtrigon** [vpelletier/pprofile#14]
Currently pprofile seems to gather ALL command line parameters it can find, e.g.:
```
$ pprofile file_metadata/wikibot/log_bot.py -search:'eth-bib' -limit:5 -dry
usage: pprofile [-h] [-o OUT] [-z ZIPFILE] [-t THREADS] [-f {text,callgrind}]
                [-v] [-s STATISTIC] [--exclude-syspath] [--exclude EXCLUDE]
                [--include INCLUDE]
                script
pprofile: error: argument -s/--statistic: invalid float value: 'earch:eth-bib'
```
As you can see pprofile takes the "-s" from "-search:'eth-bib'" does not understand what to do and by that messes up the command to execute.

I propose to not touch any of the string after and including `script`. The parameters given after `script` belong to `script` and NOT to pprofile. May be it's needed to introduce a parameter to mark from where the actual `script` command starts. E.g. like `... -c script params-and-stuff-belonging-to-script`.

**Comment by vpelletier** [comment]
Without code change, you can use "--" to stop parameter parsing:
`pprofile -- file_metadata/wikibot/log_bot.py -search:'eth-bib' -limit:5 -dry`

But I agree it would be better if pprofile simply stopped looking for arguments after the executable name. I'll check argparse doc.

**Comment by vpelletier** [comment]
b5f98c14e9e88a2ed5b1b8e7624121218c631d1f should fix this issue. Could you try it ? Then I will do a release.

**Comment by drtrigon** [comment]
Thanks! Have both tested and both work (using "--" and b5f98c1).

However the execution time of the code installed through pip on the code cloned from repo do differ - may be no big deal.

**Comment by vpelletier** [comment]
> Have tested both and they work

Thanks !

> the execution time of the code installed through pip on the code cloned from repo do differ

This is surprising, as the only changes since last release do not touch the profiling hot-spots (README, zpprofile result generation, and this argument parsing change). Could you describe a bit more the kind of difference you see ? (extra time attributed to each line inflating proportionally or not to the number of hits, overall execution time increase ratio...)

**Comment by drtrigon** [comment]
I did a run using the old and the new code and did a `diff` - it's about 24MB. So I need more detailed instructions on how to investigate.

**Comment by vpelletier** [comment]
If you are comparing the two outputs (whatever the format, annotate or callgrind) I indeed expect a lot of differences from a text point of view.

Basically, what did you initially noticed ? Just that pprofile was overall took longer to exit ? Or that the profiling details did vary somehow without the profiled code being expected to take more time on that run (for example working on a fixed and small enough data set that I/O performance does not get in the way) ?

From a pprofile point of view, I can think of two things:

- When installing an egg I expect a pyc to be generated (maybe indirectly just because of the wrapper script generated to put the "pprofile" command accessible from $PATH). This will not happen when running pprofile.py from repository because python only generates pyc files from imported modules, not the one immediately passed to the interpreter. But this should makes a very tiny difference anyway (the time needed to convert the source file into bytecode), and only on the time needed to load pprofile itself (not on how the profiled code behave).
- Maybe "pip install" would have been run with a different python interpreter than the one used when running pprofile.py from repository ?

**Comment by vpelletier** [comment]
pprofile 1.9.2 released on pipy

**Comment by drtrigon** [comment]
Sorry for not coming back to this until now; so let me answer your questions.
- I basically noticed very small timing differences (I think nothing severe sometimes only a small bit off, sometimes a factor of 3 off - but always on small values like order of 1e-5)
- when having a look at "Total duration" I noticed e.g. 1.94534s for the "old" and 4.03888s for the new code - "File duration" was 0.00112057s (0.06%) and 0.000814199s (0.02%)
- that looked odd to me; huge difference in "Total duration" but I could not find any cause in the line-by-line listing
So my guess is that this is not severe so it should be fine. But if you can figure out a test you want to me to run, just tell me.
