### ISSUE TITLE
Make context managers __enter__ return themselves

### ISSUE THREAD

**Issue by anntzer** [vpelletier/pprofile#15]
By making `Profile.__enter__` and `StatisticalThread.__enter__` return the objects themselves, their use become a tiny bit simpler:
```
prof = Profile()
with prof: ...
prof.print_stats()
```
becomes
```
with Profile() as prof: ...
prof.print_stats()
```
Likewise, for StatisticalThread, we can have
```
with StatisticalThread(StatisticalProfile(), ...) as thread: ...
thread.profile.print_stats()
```

**Comment by vpelletier** [comment]
Hi. I just pushed 2 commits (documenting profiler property + context managers) which should make this possible.

This said, I'm not sure how much I want to document this type of use: it may accidentally encourage users to call print_stats (etc) while still inside the "with" block. So I went with minimal documentation (inspired from `pydoc file`). I also wonder about making profiler read-only (using `@property`) as `profiler.total_time` gets updated in `stop()` - so swapping profiler instances will produce weird results (no idea why a user would want to do this, but it just becomes possible now that this property became officially present). Any opinion ?

**Comment by anntzer** [comment]
Well, you could make `print_stats` and friends uncallable until `__exit__` is called.  If swapping the `.profiler` attribute leads to incorrect results then in should definitely be made read-only from the user POV.

**Comment by vpelletier** [comment]
> Well, you could make `print_stats` and friends uncallable until `__exit__` is called.

Thiking more about it, it's both hard to do and probably not worth the extra complexity.

They are defined on the profiler provided to the StatisticalThread instance, and the profiler does not know which "gatherer" it is used by (which I intended to allow a single profiling instance to accumulate results from any number of gatherers). So it seems hard to get it to know whether some profiling is still happening.

Also, pprofile [hides](https://github.com/vpelletier/pprofile/blob/141d2566018c8949c89246d3745c4d3487cdcdee/pprofile.py#L297) itself from the profiling output as it would otherwise always appear (at least the lines immediately following its enabling and preceding its disabling).

> then in should definitely be made read-only

Done.
